### ISSUE TITLE
Image Resize is Changing Color

### ISSUE THREAD

**Issue by AEFeinstein** [redwarp/9-Patch-Resizer#22]
When I attempt to resize this image:
![ic_drawer_about_light](https://cloud.githubusercontent.com/assets/231180/6745468/97647664-ce8d-11e4-8fe0-28cc79345c36.png)
it comes out as this:
![ic_drawer_about_light](https://cloud.githubusercontent.com/assets/231180/6745473/abef6a58-ce8d-11e4-90a3-74816a058fff.png)

**Comment by AEFeinstein** [comment]
I believe it has to do with the image being in A8L8 format. I poked around a bit and didn't find a way of reading a bufferedimage in A8L8 format.

**Comment by redwarp** [comment]
Thanks! I'll look into it. Didn't even know about this format to begin with haha.
How did you produce the image in the first time? Toshop? Gimp? Something else (like compressing it with imageOptim or zopfli or pngcrush or...)

**Comment by redwarp** [comment]
Okkkkay! Using the term "A8L8" scared me, because all I found was reference to textures for 3D and stuff. But actually, it just means, here : greyscale PNG. So I opened an image with gimp, converted it to greyscale, saved it, used it with Resizer, and observed the same thing than with your image : fucked up output. So it's not isolated to your image, it probably works with every greyscale PNG, that's good to know!

I'll look into it, thanks for the feedback.

**Comment by AEFeinstein** [comment]
Yep, 8 bits of alpha, 8 bits of luminance. I generated this image with imagemagick's convert command. Turns out its the default format for greyscale png, but you can force it to save in ARGB too, which I did for now. Thanks for looking into it!

**Comment by redwarp** [comment]
Alright, new version 1.4.1, that should fix this. I changed the way images are opened, Toolkit instead of imageIO

**Comment by AEFeinstein** [comment]
Speedy fix. Thanks!
