### ISSUE TITLE
Here's a macOS app wrapper

### ISSUE THREAD

**Issue by EzraLopez** [redwarp/9-Patch-Resizer#28]
This is handy for me and thought I'd share it in case it is useful for someone else.

I did it following this simple tutorial here: https://youtu.be/kwdK6Dg1a_Y

Download app wrapper:
[Resizer-1.4.2.app.zip](https://github.com/redwarp/9-Patch-Resizer/files/741966/Resizer-1.4.2.app.zip)

**Comment by redwarp** [comment]
@EzraLopez Thanks for sharing! I'm still looking for a way to do it automatically. Plus there is the problem with signing and trust on mac: I can't open your app, as can seen in the screenshot, because of the latest Os Sierra security option. What I can do is add the "how to macOs app wrapper" to the readme though, in case other people are interested.

![screen shot 2017-01-31 at 14 13 54](https://cloud.githubusercontent.com/assets/1741661/22466235/b2920418-e7bf-11e6-821e-4ff5df20bc2d.png)

**Comment by EzraLopez** [comment]
Bummer! Yes, you can do that. Although, I think you should be able to run it if you go to: 
`System Settings/Security & Privacy/General/`

and select `Allow apps downloaded from: Anywhere`

**Comment by redwarp** [comment]
@EzraLopez Os Sierra is more strict now, you need to do it from command line ;-)
It became a pain, for security reasons.

As I compile from a PC anyway, I would not be able to do the proper signing that XCode requires.

**Comment by EzraLopez** [comment]
@redwarp really? I have the latest Sierra version, and the option is still there.

Well, I use macOS, let me know if I can help with anything.

**Comment by redwarp** [comment]
Closing it as we didn't update that for a while.
