### ISSUE TITLE
Density input

### ISSUE THREAD

**Issue by michelp3** [redwarp/9-Patch-Resizer#32]
Hello,

9Patch Resizer is a very practical software.

However, I do not understand the density input option

Could someone explain to me the importance of varying input density?

Thank you

**Comment by redwarp** [comment]
Basically, what is the density of the initial file.
For example, let's say you want to display an image that is 50x50 density pixel on your device.
In mdpi, it would be 50 x 50 px, in xhdpi it would be 75x75 pixels, and so on.

You would probably prepare an image that is XXDPI, meaning 150x150px, and then select the density option as xxhdpi, so that you can tell the software "Hey, my original is 3x". Then Resizer would create from that a xhdpi at 100x100, a hdpi at 75x75 and a mdpi at 50x50

**Comment by michelp3** [comment]
thank you for response but my problem is what definition for the original image? a high definition ???

**Comment by redwarp** [comment]
I'm afraid I can't help you there. You have to decide what size you want in density pixel and create an original image proportionated to that.
You should probably read this, it might help you understanding the whole density thing better: https://www.captechconsulting.com/blogs/understanding-density-independence-in-android

Cheers, I'll close this issue for now :-)
